name: CI
on:
  # 代码push的时候触发
  push:
    # main分支的时候触发
    branches: main
jobs:
  # 定义一个job，名字为CI
  CI:
    # 使用github提供给我们的机器去跑
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 拉取最新的代码
      - name: Checkout repository
        uses: actions/checkout@v2
      # 安装node环境
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      # 为node_modules设置缓存
      - name: Cache
        # 缓存命中结果会存储在steps.[id].outputs.cache-hit里，该变量在继后的step中可读
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          # 缓存文件目录的路径
          path: |
            **/node_modules
          key: ${{runner.OS}}
      # 安装依赖
      - name: Installing Dependencies
        # 如果命中缓存，就不需要安装依赖，使用缓存即可
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn
      # 打包
      - name: Build
        run: |
            yarn build
            zip -r build ./build/**
      # 产物上传服务器
      - name: Upload to Deploy Server
        uses: burnett01/rsync-deployments@4.1
        with:
         switches: -avzh
         path: public/    # 将public文件夹同步到服务器下的 PATH 路径
         remote_path: "/www/wwwroot/www.icecms.cn" #服务器的文件存放绝对路径
         remote_host: ${{ secrets.D_HOST }} #服务器域名或者IP地址
         remote_port: 22 # ssh远程端口(如果没修改过ssh远程端口，默认是22)
         remote_user: ${{ secrets.D_USER }} # 使用ssh登录的用户
         remote_key: ${{ secrets.D_PASS }}      
